---
collections:
  - name: jplevy.lab
    version: 1.2.6
  - name: ansible.controller  
  - name: ansible.posix
  - name: ansible.windows
  - name: community.hashi_vault
  - name: community.general
  - name: community.kubernetes
  - name: community.libvirt
  - name: community.windows
  - name: containers.podman
  - name: redhat_cop.controller_configuration
  - name: theforeman.foreman
